################### DGD2CMDI Configuration File ##########################

#This is a configuration file for the necessary parameters of dgd2cmdi. It
#follows the yml syntax.

################### BASE PATHS ################################################

corpora: /home/kuhn/dgd2_data_rev1233/metadata/corpora/extern
events: /home/kuhn/dgd2_data_rev1233/metadata/events/extern
speakers: /home/kuhn/dgd2_data_rev1233/metadata/speakers/extern

cmdi_schemas: /data/cmdi


################## CMDI HEADERS ##############################################

# This section defines all cmdi header information that are used in a
# generated cmdi file.

# set the MDCreator name
mdcreator: dgd2cmdi

# component registry profile id for corpora
corpus_cmdi_componentreg_id: clarin.eu:cr1:p_1430905751614

# cmdi component registry profile id for an event
event_cmdi_componentreg_id: clarin.eu:cr1:p_1430905751615

# path to xml schema for cmdi corpus validation
corpus_cmdi_componentreg_xsd: http://www.clarin.eu/cmd/ http://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/profiles/clarin.eu:cr1:p_1430905751614/xsd

# path to xmls schema for cmdi event validation
event_cmdi_componentreg_xsd: http://www.clarin.eu/cmd/ http://catalog.clarin.eu/ds/ComponentRegistry/rest/registry/profiles/clarin.eu:cr1:p_1430905751615/xsd



################# SPECIFIC RESOURCE INFORMATION ###############################

# This section contains specific resource informations that are used during the transformation
#
#resources:
#  -name: The name of the resource as depicted in the dgd2
#   description: A short description of the resource
#   dgd_corpus_path:
#   dgd_events_path:
#   dgd_speakers_path:
#   checksum_path: path to checksum csv
#   custom_stylesheet: if necessary, define a custom stylesheet path. else False.

resources:

    - name: PF
      description: The Pfeffer Corpus
      dgd_corpus_path: /home/kuhn/IDS/repos/svn/dgd2_data_rev1233/metadata/corpora/extern/PF--_extern.xml
      dgd_events_path: /home/kuhn/IDS/repos/svn/dgd2_data_rev1233/metadata/events/extern/PF
      dgd_speakers_path: /home/kuhn/IDS/repos/svn/dgd2_data_rev1233/metadata/speakers/extern/PF
      checksum_path: ...
      custom_stylesheet: False


    - name: ZW
      description: The Zwirner Corpus
      dgd_corpus_path: /home/kuhn/IDS/repos/svn/dgd2_data_rev1233/metadata/corpora/extern/ZW--_extern.xml
      dgd_events_path: /home/kuhn/IDS/repos/svn/dgd2_data_rev1233/metadata/events/extern/ZW
      dgd_speakers_path: /home/kuhn/IDS/repos/svn/dgd2_data_rev1233/metadata/speakers/extern/ZW
      checksum_path: ...
      custom_stylesheet: False

