# This file defines the resources for any 
# xslt processing via dgd2cmdi

processor: "saxon_testpath"
stylesheets:
    corpus: "corpus_xslt"
    event: "event_xslt"
    speaker: "speaker_xslt"

output-inter: "path/to/intermediate/transformation/output"

output-final: "path/to/finalized/output"

collection:
    PF:
        corpus: "testpath.xml"
        event: "testpath.xml"
        speaker: "testpath.xml"

    ZW:
        corpus: "testpath.xml"
        event: "testpath.xml"
        speaker: "testpath.xml"

