# This file defines the resources for any 
# xslt processing via dgd2cmdi

# xslt processor and stylesheet path declaration
processor: "saxon_testpath"
stylesheets:
    corpus: "corpus_xslt"
    event: "event_xslt"
    speaker: "speaker_xslt"

# output paths declarations
output-inter-corpus: "path/to/intermediate/transformation/output"
output-inter-events: ""
output-inter-speakers: ""
output-final: "path/to/finalized/output"

# resource collection declaration
collection:
    PF:
        corpus: "testpath.xml"
        event: "testpath.xml"
        speaker: "testpath.xml"

    ZW:
        corpus: "testpath.xml"
        event: "testpath.xml"
        speaker: "testpath.xml"

